### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by spencerthayer** [hoaproject/Irc#33]
Is there a working example of this IRC client?

**Comment by Hywan** [comment]
Hello,

Do you mean an example like this https://github.com/hoaproject/Irc#quick-usage, or something more complete?

**Comment by spencerthayer** [comment]
Something complete. Thanks.

**Comment by Hywan** [comment]
A complete IRC client would be difficult because of the nature of PHP. But if you want a more complete example, you can check one bot that Hoa is using almost everywhere, [Marvirc](https://github.com/hoaproject/Marvirc). It contains several commands, reacts on IRC, can do action, and you can communicate with it through WebSocket. For instance, several tools on our servers send messages to Marvirc through WebSocket to broadcast notifications on IRC, see https://github.com/hoaproject/Marvirc#possession-through-websocket-realtime-notifications.

**Comment by Hywan** [comment]
Is it OK for you or not 😃?

**Comment by spencerthayer** [comment]
we aregood! thanks
